export const GET_BOOKMARKS = 'GET_BOOKMARKS'
export const TOGGLE_SKIN = 'TOGGLE_SKIN'
export const COUNT_REQUEST = 'COUNT_REQUEST'
export const GET_GROUP = 'GET_GROUP'
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SET_TOKEN_TIME_OUT = 'SET_TOKEN_TIME_OUT'
export const SET_USER_PERMISSIONS = 'SET_USER_PERMISSIONS'

// Account settings
export const GET_ACCOUNT_INFO = 'GET_ACCOUNT_INFO'
export const UPDATE_ACCOUNT_INFO = 'UPDATE_ACCOUNT_INFO'
export const UPDATE_ACCOUNT_INFO_FROM_SETTING = 'UPDATE_ACCOUNT_INFO_FROM_SETTING'
export const UPDATE_ACCOUNT_AVATAR = 'UPDATE_ACCOUNT_AVATAR'
export const UPDATE_GENERAL_SETTING = 'UPDATE_GENERAL_SETTING'

// Project actions
export const GET_PROJECTS = 'GET_PROJECTS'
export const GET_ALL_PROJECTS = 'GET_ALL_PROJECTS'
export const GET_PROJECT_BY_ID = 'GET_PROJECT_BY_ID'
export const ADD_PROJECT = 'ADD_PROJECT'
export const EDIT_PROJECT = 'EDIT_PROJECT'
export const REMOVE_PROJECT = 'REMOVE_PROJECT'
export const GET_WEATHER_INFO = 'GET_WEATHER_INFO'
export const SET_SELECTED_PROJECT = 'SET_SELECTED_PROJECT'
export const SET_PROJECT_DATA = 'SET_PROJECT_DATA'
export const GET_ELECTRICITY = 'GET_ELECTRICITY'
export const GET_INDUSTRIAL_AREAS = 'GET_INDUSTRIAL_AREAS'
export const GET_INVESTORS = 'GET_INVESTORS'
export const GET_PROJECT_MONITORING = 'GET_PROJECT_MONITORING'

// Project - Chart actions
export const ADD_CHART_PARAM = 'ADD_CHART_PARAM'
export const REMOVE_CHART_PARAM = 'REMOVE_CHART_PARAM'
export const CHANGE_CHART_DATE_PICKER = 'CHANGE_CHART_DATE_PICKER'
export const CHANGE_CHART_TYPE = 'CHANGE_CHART_TYPE'
export const GET_PROJECT_CHART_DATA = 'GET_PROJECT_CHART_DATA'
export const GET_CHART_FILTER_TEMPLATE = 'GET_CHART_FILTER_TEMPLATE'
export const ADD_CHART_FILTER_TEMPLATE = 'ADD_CHART_FILTER_TEMPLATE'
export const UPDATE_CURRENT_CHART_TEMPLATE = 'UPDATE_CURRENT_CHART_TEMPLATE'
export const RESET_CHART_FILTER = 'RESET_CHART_FILTER'

// Customer actions
export const GET_CUSTOMERS = 'GET_CUSTOMERS'
export const GET_CUSTOMER_BY_ID = 'GET_CUSTOMER_BY_ID'
export const ADD_CUSTOMER = 'ADD_CUSTOMER'
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER'
export const INACTIVATE_CUSTOMER = 'INACTIVATE_CUSTOMER'
export const ACTIVATE_CUSTOMER = 'ACTIVATE_CUSTOMER'
export const SET_SELECTED_CUSTOMER = 'SET_SELECTED_CUSTOMER'
export const SORT_CUSTOMERS = 'SORT_CUSTOMERS'
export const SET_CUSTOMER_DATA = 'SET_CUSTOMER_DATA'
export const FILTER_CUSTOMERS = 'FILTER_CUSTOMERS'

// User actions
export const GET_USERS = 'GET_USERS'
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const GET_USER_BY_ID = 'GET_USER_BY_ID'
export const ADD_USER = 'ADD_USER'
export const EDIT_USER = 'EDIT_USER'
export const INACTIVATE_USER = 'INACTIVATE_USER'
export const ACTIVATE_USER = 'ACTIVATE_USER'
export const SET_SELECTED_USER = 'SET_SELECTED_USER'
export const SORT_USERS = 'SORT_USERS'
export const SET_USER_DATA = 'SET_USER_DATA'
export const FILTER_USERS = 'FILTER_USERS'
export const GET_USERS_ACTIVITIES = 'GET_USERS_ACTIVITIES'
export const GET_USERS_ACTIVITIES_REPORT = 'GET_USERS_ACTIVITIES_REPORT'

// Device type inverter actions
export const GET_DEVICE_TYPE_INVERTERS = 'GET_DEVICE_TYPE_INVERTERS'
export const ADD_DEVICE_TYPE_INVERTER = 'ADD_DEVICE_TYPE_INVERTER'
export const EDIT_DEVICE_TYPE_INVERTER = 'EDIT_DEVICE_TYPE_INVERTER'
export const SET_SELECTED_DEVICE_TYPE_INVERTER = 'SET_SELECTED_DEVICE_TYPE_INVERTER'
export const INACTIVE_DEVICE_TYPE_INVERTER = 'INACTIVE_DEVICE_TYPE_INVERTER'

// Device type panel actions
export const GET_DEVICE_TYPE_PANELS = 'GET_DEVICE_TYPE_PANELS'
export const ADD_DEVICE_TYPE_PANEL = 'ADD_DEVICE_TYPE_PANEL'
export const EDIT_DEVICE_TYPE_PANEL = 'EDIT_DEVICE_TYPE_PANEL'
export const SET_SELECTED_DEVICE_TYPE_PANEL = 'SET_SELECTED_DEVICE_TYPE_PANEL'
export const INACTIVE_DEVICE_TYPE_PANEL = 'INACTIVE_DEVICE_TYPE_PANEL'

// Settings project actions
export const GET_SETTINGS_PROJECTS = 'GET_SETTINGS_PROJECTS'
export const GET_SETTINGS_PROJECT_BY_ID = 'GET_SETTINGS_PROJECT_BY_ID'
export const ADD_SETTINGS_PROJECT = 'ADD_SETTINGS_PROJECT'
export const EDIT_SETTINGS_PROJECT = 'EDIT_SETTINGS_PROJECT'
export const INACTIVATE_SETTINGS_PROJECT = 'INACTIVATE_SETTINGS_PROJECT'
export const ACTIVATE_SETTINGS_PROJECT = 'ACTIVATE_SETTINGS_PROJECT'
export const SORT_PROJECTS = 'SORT_PROJECTS'
export const SET_SETTINGS_SELECTED_PROJECT = 'SET_SETTINGS_SELECTED_PROJECT'
export const SET_SETTINGS_PROJECT_DATA = 'SET_SETTINGS_PROJECT_DATA'
export const FILTER_SETTINGS_PROJECTS = 'FILTER_SETTINGS_PROJECTS'
export const GET_SETTINGS_AUTO_PROJECTS = 'GET_SETTINGS_AUTO_PROJECTS'
export const GET_SETTINGS_PENDING_APPROVE_PROJECTS = 'GET_SETTINGS_PENDING_APPROVE_PROJECTS'
export const GET_SETTINGS_PENDING_DELETE_PROJECTS = 'GET_SETTINGS_PENDING_DELETE_PROJECTS'
export const GET_SETTING_TOTAL_REQUESTS = 'GET_SETTING_TOTAL_REQUESTS'

// Settings device actions
export const GET_DEVICES = 'GET_DEVICES'
export const GET_DEVICE_BY_ID = 'GET_DEVICE_BY_ID'
export const ADD_DEVICE = 'ADD_DEVICE'
export const EDIT_DEVICE = 'EDIT_DEVICE'
export const REMOVE_DEVICE = 'REMOVE_DEVICE'
export const SET_SELECTED_DEVICE = 'SET_SELECTED_DEVICE'
export const SORT_DEVICES = 'SORT_DEVICES'
export const SET_DEVICE_DATA = 'SET_DEVICE_DATA'

// Settings meter actions
export const GET_METERS = 'GET_METERS'
export const GET_METER_BY_ID = 'GET_METER_BY_ID'
export const ADD_METER = 'ADD_METER'
export const EDIT_METER = 'EDIT_METER'
export const INACTIVATE_METER = 'INACTIVATE_METER'
export const ACTIVATE_METER = 'ACTIVATE_METER'
export const SET_SELECTED_METER = 'SET_SELECTED_METER'
export const SORT_METERS = 'SORT_METERS'
export const SET_METER_DATA = 'SET_METER_DATA'

// Settings inverter actions
export const GET_INVERTERS = 'GET_INVERTERS'
export const GET_INVERTER_BY_ID = 'GET_INVERTER_BY_ID'
export const ADD_INVERTER = 'ADD_INVERTER'
export const EDIT_INVERTER = 'EDIT_INVERTER'
export const INACTIVATE_INVERTER = 'INACTIVATE_INVERTER'
export const ACTIVATE_INVERTER = 'ACTIVATE_INVERTER'
export const SET_SELECTED_INVERTER = 'SET_SELECTED_INVERTER'
export const SET_INVERTER_DATA = 'SET_INVERTER_DATA'
export const GET_INVERTER_TYPES = 'GET_INVERTER_TYPES'

// Settings panel actions
export const GET_PANELS = 'GET_PANELS'
export const GET_PANEL_BY_ID = 'GET_PANEL_BY_ID'
export const ADD_PANEL = 'ADD_PANEL'
export const EDIT_PANEL = 'EDIT_PANEL'
export const INACTIVATE_PANEL = 'INACTIVATE_PANEL'
export const ACTIVATE_PANEL = 'ACTIVATE_PANEL'
export const SET_SELECTED_PANEL = 'SET_SELECTED_PANEL'
export const SET_PANEL_DATA = 'SET_PANEL_DATA'
export const GET_PANEL_TYPES = 'GET_PANEL_TYPES'

// Settings monitoring meter actions
export const GET_MONITORING_METERS = 'GET_MONITORING_METERS'
export const GET_MONITORING_METER_BY_ID = 'GET_MONITORING_METER_BY_ID'
export const ADD_MONITORING_METER = 'ADD_MONITORING_METER'
export const EDIT_MONITORING_METER = 'EDIT_MONITORING_METER'
export const REMOVE_MONITORING_METER = 'REMOVE_MONITORING_METER'
export const SET_SELECTED_MONITORING_METER = 'SET_SELECTED_MONITORING_METER'
export const SET_MONITORING_METER_DATA = 'SET_MONITORING_METER_DATA'
export const GET_DAILY_YIELD = 'GET_DAILY_YIELD'
export const GET_DAILY_YIELD_BY_PROJECT = 'GET_DAILY_YIELD_BY_PROJECT'
export const GET_MONTHLY_YIELD_BY_PROJECT = 'GET_MONTHLY_YIELD_BY_PROJECT'
export const GET_YESTERDAY_DAILY_YIELD_BY_PROJECT = 'GET_YESTERDAY_DAILY_YIELD_BY_PROJECT'

// Settings monitoring inverter actions
export const GET_MONITORING_INVERTERS = 'GET_MONITORING_INVERTERS'
export const GET_MONITORING_INVERTERS_MULTI_TIMES = 'GET_MONITORING_INVERTERS_MULTI_TIMES'
export const GET_MONITORING_INVERTER_BY_ID = 'GET_MONITORING_INVERTER_BY_ID'
export const GET_LATEST_MONITORING_INVERTER_BY_ID = 'GET_LATEST_MONITORING_INVERTER_BY_ID'
export const ADD_MONITORING_INVERTER = 'ADD_MONITORING_INVERTER'
export const EDIT_MONITORING_INVERTER = 'EDIT_MONITORING_INVERTER'
export const REMOVE_MONITORING_INVERTER = 'REMOVE_MONITORING_INVERTER'
export const SET_SELECTED_MONITORING_INVERTER = 'SET_SELECTED_MONITORING_INVERTER'
export const SET_MONITORING_INVERTER_DATA = 'SET_MONITORING_INVERTER_DATA'
export const GET_PANELS_BY_INVERTER_ID = 'GET_PANELS_BY_INVERTER_ID'

// Alerts actions
export const GET_ALERTS = 'GET_ALERTS'
export const GET_ALERTS_FOR_INVERTER_PANEL = 'GET_ALERTS_FOR_INVERTER_PANEL'
export const GET_HISTORY_ALERTS = 'GET_HISTORY_ALERTS'
export const UPDATE_FIREBASE_MESSAGE = 'UPDATE_FIREBASE_UPDATE'
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS'
export const MARK_ALL_READ = 'MARK_ALL_READ'
export const MARK_AS_READ = 'MARK_AS_READ'
export const GET_ALERT_NOTES = 'GET_ALERT_NOTES'
export const ADD_ALERT_NOTE = 'ADD_ALERT_NOTE'

// Report actions
export const GET_PROJECTS_QUANTITY_REPORT = 'GET_PROJECTS_QUANTITY_REPORT'
export const GET_PROJECTS_OPERATIONAL_REPORT = 'GET_PROJECTS_OPERATIONAL_REPORT'
export const GET_GENERAL_REPORT = 'GET_GENERAL_REPORT'
export const CLEAR_OPERATION_REPORT = 'CLEAR_OPERATION_REPORT'
export const CLEAR_YIELD_REPORT = 'CLEAR_YIELD_REPORT'
export const CLEAR_GENERAL_REPORT = 'CLEAR_GENERAL_REPORT'

// Sensor setting
export const GET_SENSOR = 'GET_SENSOR'

// billing
export const FETCH_COMPANY_REQUEST = 'FETCH_COMPANY_REQUEST'
export const SET_OPERATION_UNIT_PARAMS = 'SET_OPERATION_UNIT_PARAMS'
export const SET_SELECTED_OPERATION_UNIT = 'SET_SELECTED_OPERATION_UNIT'

export const FETCH_CUSTOMERS_REQUEST = 'FETCH_CUSTOMERS_REQUEST'
export const SET_SELECTED_BILLING_CUSTOMER = 'SET_SELECTED_BILLING_CUSTOMER'
//roofvendor
export const SET_CUSTOMER_PARAMS = 'SET_CUSTOMER_PARAMS'

export const SET_BILLING_SETTING_PARAMS = 'SET_BILLING_SETTING_PARAMS'

export const SET_ROOF_VENDOR_PARAMS = 'SET_ROOF_VENDOR_PARAMS'
export const FETCH_ROOF_RENTAL_UNIT_REQUEST = 'FETCH_ROOF_RENTAL_UNIT_REQUEST'
export const SET_SELECTED_ROOF_VENDOR = 'SET_SELECTED_ROOF_VENDOR'
export const FETCH_SETTINGS_REQUEST = 'FETCH_SETTINGS_REQUEST'
export const SET_SETTING_BY_CODE = 'SET_SETTING_BY_CODE'
export const SET_SELECTED_BILLING_SETTING = 'SET_SELECTED_BILLING_SETTING'
export const SET_ROOF_RENTAL_UNIT_PARAMS = 'SET_ROOF_RENTAL_UNIT_PARAMS'

export const SET_CONTACT = 'SET_CONTACT'

export const SET_CLOCK = 'SET_CLOCK'

//project
export const FETCH_PROJECT_REQUEST = 'FETCH_PROJECT_REQUEST'
export const SET_CONTRACT_OF_BILLING_PROJECT = 'SET_CONTRACT_OF_BILLING_PROJECT'

export const SET_SELECTED_BILLING_PROJECT = 'SET_SELECTED_BILLING_PROJECT'
export const SET_PROJECT_PARAMS = 'SET_PROJECT_PARAMS'

//contract
export const SET_SELECTED_CONTRACT = 'SET_SELECTED_CONTRACT'

// form
export const SET_FORM_DIRTY = 'SET_FORM_DIRTY'

export const FETCH_METER_REQUEST = 'FETCH_METER_REQUEST'

export const FETCH_METER_METRIC_REQUEST = 'FETCH_METER_METRIC_REQUEST'
export const RESET_DATA_METER_METRIC_REQUEST = 'RESET_DATA_METER_METRIC_REQUEST'

// input clock index

//role
export const FETCH_ROLE_REQUEST = 'FETCH_ROLE_REQUEST'
export const SET_SELECTED_ROLE = 'SET_SELECTED_ROLE'
export const SELECTED_ROLE = 'SELECTED_ROLE'

// PERMISSION
export const SET_ALL_PERMISSION = 'SET_ALL_PERMISSION'
export const FETCH_USER_ROLE_REQUEST = 'FETCH_USER_ROLE_REQUEST'
export const RESET_USER_ROLE = 'RESET_USER_ROLE'
export const RESET_PERMISSION_GROUP_PARAM = 'RESET_PERMISSION_GROUP_PARAM'


// USER FEATURE
export const SET_ALL_USER_FEATURE = 'SET_ALL_USER_FEATURE'
export const SET_IS_FETCHED_PERMISSION = 'SET_IS_FETCHED_PERMISSION'

export const SET_ALL_USER_ACTION = 'SET_ALL_USER_ACTION'

export const FETCH_INPUT_CLOCK_INDEX = 'FETCH_INPUT_CLOCK_INDEX'
export const SET_INPUT_CLOCK_INDEX_PARAMS = 'SET_INPUT_CLOCK_INDEX_PARAMS'
export const SET_SELECTED_INPUT_CLOCK_INDEX = 'SET_SELECTED_INPUT_CLOCK_INDEX'

// Send command to inverter
export const SEND_COMMAND_TO_INVERTER = 'SEND_COMMAND_TO_INVERTER'