export const CUSTOM_HISTORY = {
  SHOW_NONE: 0,
  SHOW_OVERVIEW: 1,
  SHOW_CUSTOMERS: 2,
  SHOW_PROJECTS: 3,
  SHOW_PROJECT_OVERVIEW: 4,
  SHOW_PROJECT_INFO: 5,
  SHOW_PROJECT_DEVICE: 6,
  SHOW_PROJECT_ALERT: 7,
  SHOW_PROJECT_MAINTENANCE: 8
}