export const USER_FEATURE = {
  CONFIG: 'CONFIG',
  OPE_CO: 'OPERATION_COMPANY',
  CUSTOMER: 'CUSTOMER',
  RENTAL_COMPANY: 'RENTAL_COMPANY',
  PROJECT: 'PROJECT',
  METER: 'METER',
  BILL_PARAMS: 'BILL_PARAMS',
  BILL_ADMIN: 'BILL_ADMIN',
  RENTAL_ADMIN: 'RENTAL_ADMIN',
  INVOICE_ADMIN: 'INVOICE_ADMIN',
  BILL_NOTICE: 'BILL_NOTICE',
  RENTAL_NOTICE: 'RENTAL_NOTICE',
  METER_METRICS: 'METER_METRICS',
  INVOICE_CUSTOMER: 'INVOICE_CUSTOMER',
  GROUP_MANAGER: 'GROUP_MANAGER',
  ROLE_ASSIGNMENT: 'ROLE_ASSIGNMENT'
}

export const USER_ACTION = {
  VIEW_ALL: 'VIEW_ALL',
  VIEW: 'VIEW',
  DETAIL: 'DETAIL',
  EDIT: 'EDIT',
  DELETE: 'DELETE',
  CREATE: 'CREATE',
  IMPORT: 'IMPORT',
  EXPORT: 'EXPORT',
  SEND: 'SEND',
  APPROVE: 'APPROVE'
}
